import { Ionicons } from '@expo/vector-icons';
import { Alert, Pressable, ScrollView, Share, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const Stat = ({ label, value }: { label: string; value: string }) => <View className="flex-1 rounded-2xl bg-slate-50 p-4"><Text className="text-xs text-slate-500">{label}</Text><Text className="mt-2 text-xl font-extrabold text-slate-900">{value}</Text></View>;
const Row = ({ icon, title, text, onPress }: { icon: keyof typeof Ionicons.glyphMap; title: string; text: string; onPress?: () => void }) => <Pressable onPress={onPress} className="flex-row items-center border-b border-slate-100 px-5 py-4"><View className="h-10 w-10 items-center justify-center rounded-xl bg-blue-50"><Ionicons name={icon} size={20} color="#2563EB" /></View><View className="ml-3 flex-1"><Text className="font-bold text-slate-900">{title}</Text><Text className="mt-1 text-xs leading-4 text-slate-500">{text}</Text></View><Ionicons name="chevron-forward" size={18} color="#94A3B8" /></Pressable>;

export default function AffiliateScreen() {
  const shareLink = async () => { try { await Share.share({ message: 'Join me on STOCKASTICS and explore our stock market intelligence. Referral link: STOCKASTICS_REFERRAL_LINK' }); } catch {} };
  return <SafeAreaView className="flex-1 bg-slate-50" edges={['top']}>
    <View className="border-b border-slate-100 bg-white px-5 py-4"><Text className="text-2xl font-extrabold text-slate-900">Affiliate</Text><Text className="mt-1 text-sm text-slate-500">Invite others and manage your referrals</Text></View>
    <ScrollView contentContainerClassName="pb-10 pt-5">
      <View className="mx-5 rounded-3xl bg-blue-700 p-6"><View className="h-12 w-12 items-center justify-center rounded-2xl bg-white/20"><Ionicons name="people" size={25} color="white" /></View><Text className="mt-4 text-2xl font-extrabold text-white">Grow with STOCKASTICS</Text><Text className="mt-2 text-sm leading-5 text-blue-100">Share your referral link with people who may find STOCKASTICS useful.</Text><Pressable onPress={shareLink} className="mt-5 rounded-xl bg-white px-4 py-3"><Text className="text-center font-bold text-blue-700">Share Referral Link</Text></Pressable></View>
      <View className="mx-5 mt-5 flex-row gap-3"><Stat label="Referrals" value="0" /><Stat label="Active" value="0" /><Stat label="Earnings" value="$0.00" /></View>
      <View className="mx-5 mt-5 rounded-2xl border border-slate-200 bg-white p-5"><Text className="font-extrabold text-slate-900">Your Referral Link</Text><View className="mt-3 flex-row items-center rounded-xl bg-slate-100 px-4 py-3"><Text className="flex-1 text-sm text-slate-600" numberOfLines={1}>STOCKASTICS_REFERRAL_LINK</Text><Pressable onPress={() => Alert.alert('Referral Link','Copy will be connected to the native clipboard service.')}><Text className="font-bold text-blue-700">Copy</Text></Pressable></View></View>
      <View className="mx-5 mt-5 rounded-2xl border border-slate-200 bg-white"><Text className="px-5 pb-2 pt-5 text-lg font-extrabold text-slate-900">Affiliate</Text><Row icon="person-add-outline" title="My Referrals" text="View people who joined through your referral link." onPress={() => Alert.alert('My Referrals','Referral activity will appear here.')} /><Row icon="wallet-outline" title="Earnings & Payouts" text="View eligible commissions and payout status." onPress={() => Alert.alert('Earnings & Payouts','Eligible earnings and payout history will appear here.')} /><Row icon="help-circle-outline" title="How Affiliate Works" text="Learn how referrals, eligibility and payouts work." onPress={() => Alert.alert('How Affiliate Works','Share your referral link. Eligible referred subscriptions are attributed to your account according to the affiliate terms.')} /></View>
      <View className="mx-5 mt-5 rounded-2xl bg-blue-50 p-5"><Text className="font-extrabold text-slate-900">Affiliate Terms</Text><Text className="mt-2 text-xs leading-5 text-slate-600">Referral rewards, eligibility, attribution, payment thresholds and payout timing are governed by the STOCKASTICS Affiliate Terms.</Text><Pressable onPress={() => Alert.alert('Affiliate Terms','Affiliate terms will open here.')} className="mt-3"><Text className="font-bold text-blue-700">View Affiliate Terms</Text></Pressable></View>
    </ScrollView>
  </SafeAreaView>;
}
