import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const categories = [
  ['Retail', '/retail-signals'], ['IPO', '/ipo-signals'], ['Buyback', '/buyback-signals'],
  ['Sentiment', '/sentiment-signals'], ['Ex-Div', '/ex-dividend-signals'], ['Income', '/income-signals'],
] as const;

const demoSignals = [
  { ticker: 'AAPL', name: 'Apple Inc.', confidence: 92, price: '$189.42', time: 'Today, 08:42 AM' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation', confidence: 88, price: '$124.18', time: 'Today, 08:31 AM' },
  { ticker: 'TSLA', name: 'Tesla Inc.', confidence: 87, price: '$341.06', time: 'Today, 08:17 AM' },
];

export default function RetailSignalsScreen() {
  return (
    <SafeAreaView className="flex-1 bg-slate-50" edges={['top']}>
      <View className="flex-row items-center px-5 pt-4"><Pressable onPress={() => router.back()} className="mr-3 h-10 w-10 items-center justify-center rounded-full bg-white"><Ionicons name="arrow-back" size={20} color="#0F172A" /></Pressable><View><Text className="text-2xl font-extrabold text-slate-900">Retail Signals</Text><Text className="text-xs text-slate-500">Retail market BUY opportunities</Text></View></View>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} className="mt-5 max-h-20" contentContainerClassName="gap-2 px-5">
        {categories.map(([label, route], i) => <Pressable key={route} onPress={() => router.push(route as never)} className={`min-w-[82px] items-center rounded-2xl px-3 py-3 ${i === 0 ? 'bg-blue-700' : 'border border-slate-200 bg-white'}`}><Text className={`text-xs font-bold ${i === 0 ? 'text-white' : 'text-slate-700'}`}>{label}</Text></Pressable>)}
      </ScrollView>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerClassName="px-5 pb-10 pt-5">
        <View className="mb-4 flex-row items-center justify-between"><Text className="text-lg font-extrabold text-slate-900">Latest BUY Signals</Text><View className="rounded-full bg-emerald-50 px-3 py-2"><Text className="text-xs font-extrabold text-emerald-600">LIVE</Text></View></View>
        {demoSignals.map((signal) => <Pressable key={signal.ticker} className="mb-3 rounded-2xl bg-white p-5 active:bg-slate-100"><View className="flex-row items-center justify-between"><View className="flex-row items-center"><View className="h-12 w-12 items-center justify-center rounded-xl bg-blue-50"><Text className="text-xs font-extrabold text-blue-700">{signal.ticker}</Text></View><View className="ml-3"><Text className="font-extrabold text-slate-900">{signal.name}</Text><Text className="mt-1 text-xs text-slate-400">{signal.time}</Text></View></View><View className="items-end"><Text className="font-extrabold text-emerald-600">BUY</Text><Text className="mt-1 text-xs font-bold text-slate-500">{signal.confidence}% confidence</Text></View></View><View className="mt-4 flex-row items-center justify-between border-t border-slate-100 pt-3"><Text className="text-xs text-slate-400">Reference price</Text><Text className="font-bold text-slate-800">{signal.price}</Text></View></Pressable>)}
        <View className="mt-2 rounded-2xl border border-slate-200 bg-white p-4"><Text className="text-xs leading-5 text-slate-500">Signals are generated by independent strategies. This page displays BUY opportunities only. Market prices may change after a signal is generated.</Text></View>
      </ScrollView>
    </SafeAreaView>
  );
}
