import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const categories = [
  ['Retail', '/retail-signals'], ['IPO', '/ipo-signals'], ['Buyback', '/buyback-signals'],
  ['Sentiment', '/sentiment-signals'], ['Ex-Div', '/ex-dividend-signals'], ['Income', '/income-signals'],
] as const;
const demoSignals = [
  { ticker: 'META', name: 'Meta Platforms, Inc.', confidence: 91, entry: '$450.00 - $520', time: 'Today, 09:12 AM' },
  { ticker: 'AMZN', name: 'Amazon.com, Inc.', confidence: 89, entry: '$210.00 - $235', time: 'Today, 08:42 AM' },
  { ticker: 'PYPL', name: 'PayPal Holdings, Inc.', confidence: 87, entry: '$72.00 - $84', time: 'Today, 08:31 AM' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation', confidence: 88, entry: '$118.00 - $132', time: 'Today, 08:17 AM' },
];
const cardStyles = ['border-red-200 bg-red-50', 'border-blue-200 bg-blue-50', 'border-emerald-200 bg-emerald-50', 'border-violet-200 bg-violet-50'];

export default function RetailSignalsScreen() {
  return <SafeAreaView className="flex-1 bg-slate-50" edges={['top']}>
    <View className="flex-row items-center justify-between px-5 pt-4">
      <View className="flex-row items-center"><Pressable onPress={() => router.back()} className="mr-3 h-10 w-10 items-center justify-center rounded-full bg-white"><Ionicons name="arrow-back" size={20} color="#0F172A" /></Pressable><View><Text className="text-2xl font-extrabold text-slate-900">Retail Signals</Text><Text className="text-xs text-slate-500">Intraday BUY opportunities</Text></View></View>
      <Pressable onPress={() => router.push('/how-it-works?type=retail' as never)} className="rounded-xl bg-blue-700 px-3 py-2"><Text className="text-xs font-extrabold text-white">How it works</Text></Pressable>
    </View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} className="mt-5 max-h-20" contentContainerClassName="gap-2 px-5">{categories.map(([label, route], i) => <Pressable key={route} onPress={() => router.push(route as never)} className={`min-w-[82px] items-center rounded-2xl px-3 py-3 ${i === 0 ? 'bg-blue-700' : 'border border-slate-200 bg-white'}`}><Text className={`text-xs font-bold ${i === 0 ? 'text-white' : 'text-slate-700'}`}>{label}</Text></Pressable>)}</ScrollView>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerClassName="px-5 pb-10 pt-5">
      <View className="mb-4 rounded-2xl bg-blue-700 p-5"><View className="flex-row items-center"><Ionicons name="flash" size={19} color="#86EFAC" /><Text className="ml-2 text-xs font-extrabold tracking-wider text-emerald-200">DAY TRADING</Text></View><Text className="mt-2 text-xl font-extrabold text-white">Retail BUY Signals</Text><Text className="mt-1 text-sm leading-5 text-blue-100">Our retail strategy identifies stocks with an expected upward move during the trading day.</Text></View>
      <Text className="mb-3 text-lg font-extrabold text-slate-900">Latest BUY Signals</Text>
      {demoSignals.map((s, i) => <View key={s.ticker} className={`mb-3 rounded-2xl border p-5 ${cardStyles[i % cardStyles.length]}`}><View className="flex-row items-center justify-between"><View><Text className="text-xl font-extrabold text-slate-900">{s.ticker}</Text><Text className="mt-1 text-xs text-slate-600">{s.name}</Text></View><Text className="rounded-full bg-white/80 px-3 py-1 text-xs font-extrabold text-emerald-700">BUY</Text></View><View className="mt-4 gap-2"><Text className="text-sm text-slate-600">Signal: <Text className="font-extrabold text-emerald-700">BUY</Text></Text><Text className="text-sm text-slate-600">Company: <Text className="font-bold text-slate-900">{s.name}</Text></Text><Text className="text-sm text-slate-600">Entry: <Text className="font-extrabold text-slate-900">{s.entry}</Text></Text><Text className="text-sm text-slate-600">Country: <Text className="font-bold text-slate-900">USA</Text></Text><Text className="text-sm text-slate-600">Exchange: <Text className="font-bold text-slate-900">NASDAQ</Text></Text><Text className="text-xs text-slate-500">Generated {s.time} · Strategy confidence {s.confidence}%</Text></View></View>)}
      <View className="mt-1 rounded-2xl border border-slate-200 bg-white p-4"><Text className="text-xs leading-5 text-slate-500">Retail Signals are designed for day trading. Entry prices are reference ranges generated by the strategy and may differ from live market prices. Not financial advice.</Text></View>
    </ScrollView>
  </SafeAreaView>;
}
