import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const categories=[{key:'retail',label:'Retail',route:'/retail-signals',icon:'storefront-outline' as const},{key:'ipo',label:'IPO',route:'/ipo-signals',icon:'rocket-outline' as const},{key:'buyback',label:'Buyback',route:'/buyback-signals',icon:'repeat-outline' as const},{key:'sentiment',label:'Sentiment',route:'/sentiment-signals',icon:'people-outline' as const},{key:'ex-dividend',label:'Ex-Div',route:'/ex-dividend-signals',icon:'cash-outline' as const},{key:'income',label:'Income',route:'/income-signals',icon:'wallet-outline' as const}];

export default function SignalsScreen(){
  const params=useLocalSearchParams<{religious?:string}>();
  const religious=params.religious==='halal'||params.religious==='haram'?params.religious:undefined;
  const modeLabel=religious?(religious==='halal'?'Halal':'Haram'):undefined;
  const modeColor=religious==='haram'?'#DC2626':'#16A34A';
  const openCategory=(item:typeof categories[number])=>religious?router.push({pathname:'/religious-signals',params:{religious,category:item.key}} as never):router.push(item.route as never);
  return <SafeAreaView className="flex-1 bg-slate-50" edges={['top']}><View className="px-5 pt-4"><Text className="text-2xl font-extrabold text-slate-900">{modeLabel?`${modeLabel} Signals`:'Signals'}</Text><Text className="mt-1 text-sm text-slate-500">{modeLabel?`Only ${modeLabel}-classified stocks are eligible for this signal experience.`:'Select a signal category to explore market opportunities.'}</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} className="mt-5 max-h-20" contentContainerClassName="gap-2 px-5">{categories.map((item,index)=><Pressable key={item.key} onPress={()=>openCategory(item)} className={`min-w-[88px] items-center rounded-2xl px-3 py-3 ${index===0?'bg-blue-700':'border border-slate-200 bg-white'}`}><Ionicons name={item.icon} size={20} color={index===0?'#FFFFFF':modeColor}/><Text className={`mt-1 text-xs font-bold ${index===0?'text-white':'text-slate-700'}`}>{item.label}</Text></Pressable>)}</ScrollView><ScrollView showsVerticalScrollIndicator={false} contentContainerClassName="px-5 pb-8 pt-5"><View className="mb-5 flex-row items-center justify-between"><View><Text className="text-lg font-extrabold text-slate-900">{modeLabel?`${modeLabel} BUY Signals`:'Retail Signals'}</Text><Text className="mt-1 text-sm text-slate-500">Current BUY opportunities</Text></View><View style={{backgroundColor:`${modeColor}14`}} className="rounded-full px-3 py-2"><Text style={{color:modeColor}} className="text-xs font-extrabold">BUY ONLY</Text></View></View><Pressable onPress={()=>openCategory(categories[0])} className="rounded-2xl bg-white p-5 active:bg-slate-100"><View className="flex-row items-center justify-between"><View className="h-11 w-11 items-center justify-center rounded-xl bg-emerald-50"><Ionicons name="trending-up" size={22} color="#059669"/></View><Ionicons name="chevron-forward" size={20} color="#94A3B8"/></View><Text className="mt-4 text-lg font-extrabold text-slate-900">View {modeLabel?`${modeLabel} `:''}Retail BUY Signals</Text><Text className="mt-1 leading-5 text-slate-500">{modeLabel?`Open the filtered retail feed. Only explicitly ${modeLabel}-classified stocks are eligible.`:'Open the retail signal feed to see available BUY opportunities and their market details.'}</Text></Pressable><View className="mt-4 rounded-2xl border border-slate-200 bg-white p-5"><View className="flex-row items-center"><Ionicons name="shield-checkmark-outline" size={20} color="#1E3A8A"/><Text className="ml-2 font-bold text-slate-800">Independent strategies</Text></View><Text className="mt-2 text-sm leading-5 text-slate-500">Each strategy operates independently. In religious mode, a stock must first pass the selected screening classification before its signal can be displayed.</Text></View></ScrollView></SafeAreaView>}
