import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function StockMarketView() {
  const { ticker='META', company='Meta Platforms, Inc.', country='USA', exchange='NASDAQ', price='450.00', change='+2.84%', currency='$' } = useLocalSearchParams<{ticker:string;company:string;country:string;exchange:string;price:string;change:string;currency:string}>();
  const positive = String(change).startsWith('+');
  const symbol = currency || (country === 'Nigeria' ? '₦' : '$');
  return <SafeAreaView className="flex-1 bg-slate-50" edges={['top']}><View className="flex-row items-center px-5 pt-4"><Pressable onPress={() => router.back()} className="mr-3 h-10 w-10 items-center justify-center rounded-full bg-white"><Ionicons name="arrow-back" size={20} color="#0F172A"/></Pressable><View className="flex-1"><Text className="text-2xl font-extrabold text-slate-900">{ticker}</Text><Text className="text-xs text-slate-500">{company} · {exchange}</Text></View><Pressable className="h-10 w-10 items-center justify-center rounded-full bg-white"><Ionicons name="star-outline" size={20} color="#2563EB"/></Pressable></View><ScrollView contentContainerClassName="px-5 pb-10 pt-5"><View className="rounded-3xl bg-white p-5"><Text className="text-xs font-bold text-slate-500">CURRENT PRICE</Text><View className="mt-1 flex-row items-end justify-between"><Text className="text-3xl font-extrabold text-slate-900">{symbol}{price}</Text><Text className={`rounded-full px-3 py-2 text-sm font-extrabold ${positive ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'}`}>{change}</Text></View><View className="mt-6 h-56 items-center justify-center rounded-2xl bg-slate-50"><Ionicons name="analytics-outline" size={42} color="#2563EB"/><Text className="mt-3 font-bold text-slate-700">Price movement chart</Text><Text className="mt-1 text-xs text-slate-500">Live chart data connects to the configured stock API.</Text></View><View className="mt-4 flex-row gap-2"><Pressable className="flex-1 rounded-xl bg-blue-700 py-3"><Text className="text-center text-xs font-bold text-white">1D</Text></Pressable><Pressable className="flex-1 rounded-xl bg-slate-100 py-3"><Text className="text-center text-xs font-bold text-slate-600">1W</Text></Pressable><Pressable className="flex-1 rounded-xl bg-slate-100 py-3"><Text className="text-center text-xs font-bold text-slate-600">1M</Text></Pressable><Pressable className="flex-1 rounded-xl bg-slate-100 py-3"><Text className="text-center text-xs font-bold text-slate-600">1Y</Text></Pressable></View></View><View className="mt-4 flex-row flex-wrap justify-between gap-y-3">{[['Market Status','Open'],['Country',country],['Exchange',exchange],['Day Range',`${symbol}${country === 'Nigeria' ? '5,700 – 5,900' : '441.20 – 455.80'}`],['Volume',country === 'Nigeria' ? '2.4M' : '18.4M'],['Market Cap',country === 'Nigeria' ? '₦2.1T' : '$1.3T']].map(([label,value])=><View key={label} className="w-[48%] rounded-2xl bg-white p-4"><Text className="text-xs text-slate-500">{label}</Text><Text className="mt-1 font-extrabold text-slate-900">{value}</Text></View>)}</View><View className="mt-4 rounded-2xl border border-blue-100 bg-blue-50 p-4"><Text className="font-extrabold text-blue-900">About this market</Text><Text className="mt-1 text-sm leading-5 text-blue-800">Review price movement and available market statistics for {ticker}. Market data may be delayed depending on the provider.</Text></View></ScrollView></SafeAreaView>;
}
